name: Actualizar Mapa de Siniestros

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas folium scikit-learn numpy osmnx

      - name: Generar mapa
        run: python generar_mapa.py

      - name: Publicar cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/index.html
          git diff --staged --quiet || git commit -m "Mapa actualizado automaticamente"
          git push
